name: flutter_photokit
description: Flutter plugin for interacting with PhotoKit on iOS.
author: Crater Dev Team <dev@crater.land>
homepage: https://github.com/kmorkos/flutter_photokit
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: land.crater.flutterphotokit
    pluginClass: FlutterPhotokitPlugin
